cartpole1:
  env_ID: CartPole-v1
  replay_memory_size: 100000
  mini_batch_size: 32
  epsilon_init: 1
  epsilon_min: 0.05
  epsilon_decay: 0.9995
  network_sync_rate: 10
  learning_rate: 0.001
  discount_factor: 0.99
  stop_on_reward: 100000
  fc1_nodes: 10

flappybird1:
  env_ID: FlappyBird-v0
  replay_memory_size: 100000
  mini_batch_size: 32
  epsilon_init: 1
  epsilon_min: 0.05
  epsilon_decay: 0.99_99_5
  network_sync_rate: 10
  learning_rate: 0.0001
  discount_factor: 0.99
  stop_on_reward: 100000
  fc1_nodes: 512
  env_make_params:
    use_lidar: False
  enable_double_dqn: True